In [ ]:
import pandas as pd
import numpy as np

#### Q1

In [ ]:

arr_rand=np.random.randint(low=1,high=10,size=(4,4))
df=pd.DataFrame(arr_rand,columns=[1,2,3,4], index=[1,2,3,4])
df

   1  2  3  4
1  1  9  8  3
2  4  3  2  3
3  6  4  1  4
4  6  8  2  5

### Q2

In [ ]:

df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
1               1               9               8               3
2               4               3               2               3
3               6               4               1               4
4               6               8               2               5

### Q3

In [ ]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000         4.00000        4.000000        4.000000
mean         4.250000         6.00000        3.250000        3.750000
std          2.362908         2.94392        3.201562        0.957427
min          1.000000         3.00000        1.000000        3.000000
25%          3.250000         3.75000        1.750000        3.000000
50%          5.000000         6.00000        2.000000        3.500000
75%          6.000000         8.25000        3.500000        4.250000
max          6.000000         9.00000        8.000000        5.000000

### Q4

In [ ]:
display(df.isnull())
print(df.dtypes)

   Random value 1  Random value 2  Random value 3  Random value 4
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False
4           False           False           False           False

Random value 1    int64
Random value 2    int64
Random value 3    int64
Random value 4    int64
dtype: object

### Q5

In [ ]:
display(df.loc[:,['Random value 2','Random value 3']])

   Random value 2  Random value 3
1               6               2
2               1               1
3               6               9
4               5               7

In [ ]:
display(df.iloc[:, 1: 3])

   Random value 2  Random value 3
1               6               2
2               1               1
3               6               9
4               5               7